<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import Layout from '../Layout.vue';
import AccountingApi from './AccountingApi';

defineProps({ page: { type: String, default: 'expenses' }, title: { type: String, default: 'Expenses, Income and Bank Reconciliation' } });

const activeTab = ref('expenses');
const loading = ref(false);
const saving = ref(false);
const errors = ref({});
const refs = ref({ expense_categories: [], income_categories: [], expense_accounts: [], income_accounts: [], cash_bank_accounts: [], branches: [], suppliers: [], customers: [] });
const expenses = ref([]);
const incomes = ref([]);
const recurring = ref([]);
const pettyCash = ref([]);
const imports = ref([]);
const statementLines = ref([]);
const reconciliations = ref([]);
const report = ref({ expense_summary: {}, income_summary: {} });
const filters = reactive({ search: '', status: '', category_id: '', date_from: '', date_to: '' });

const expenseForm = reactive({
    id: null, branch_id: '', expense_date: new Date().toISOString().slice(0, 10), expense_category_id: '', expense_account_id: '',
    paid_from_account_id: '', party_name: '', supplier_id: '', employee_id: '', invoice_number: '', invoice_date: '',
    payment_mode: 'cash', reference_number: '', tax_type: 'exclusive', tds_applicable: false, tds_rate: 0,
    payment_status: 'paid', status: 'draft', narration: '',
    items: [{ expense_category_id: '', expense_account_id: '', description: '', quantity: 1, rate: 0, discount_amount: 0, gst_rate: 0, cess_amount: 0 }],
});
const incomeForm = reactive({ id: null, branch_id: '', income_date: new Date().toISOString().slice(0, 10), income_category_id: '', income_account_id: '', received_into_account_id: '', customer_id: '', party_name: '', payment_mode: 'cash', reference_number: '', tax_type: 'exclusive', taxable_amount: 0, non_taxable_amount: 0, cgst_amount: 0, sgst_amount: 0, igst_amount: 0, cess_amount: 0, total_amount: 0, status: 'draft', narration: '' });
const expenseCategoryForm = reactive({ id: null, parent_id: '', category_code: '', category_name: '', expense_account_id: '', description: '', status: 'active' });
const incomeCategoryForm = reactive({ id: null, parent_id: '', category_code: '', category_name: '', income_account_id: '', description: '', status: 'active' });
const recurringForm = reactive({ id: null, branch_id: '', template_name: '', expense_category_id: '', expense_account_id: '', paid_from_account_id: '', supplier_id: '', employee_id: '', frequency: 'monthly', interval_value: 1, start_date: new Date().toISOString().slice(0, 10), next_run_date: new Date().toISOString().slice(0, 10), end_date: '', amount: 0, tax_type: 'exclusive', gst_rate: 0, auto_create_draft: true, auto_post: false, approval_required: true, status: 'active', narration: '' });
const pettyForm = reactive({ branch_id: '', employee_id: '', cash_account_id: '', advance_date: new Date().toISOString().slice(0, 10), amount: 0, purpose: '', status: 'draft' });
const importForm = reactive({ bank_account_id: '', file_name: '', statement_start_date: '', statement_end_date: '', opening_balance: '', closing_balance: '', lines: [{ transaction_date: new Date().toISOString().slice(0, 10), description: '', reference_number: '', debit_amount: 0, credit_amount: 0, running_balance: '' }] });
const reconForm = reactive({ bank_account_id: '', statement_start_date: '', statement_end_date: '', statement_closing_balance: 0, items: [{ bank_statement_line_id: '', journal_entry_id: '', matched_amount: 0, match_type: 'manual', remarks: '' }] });

const tabs = ['expenses', 'income', 'categories', 'recurring', 'petty cash', 'bank import', 'reconciliation', 'reports'];
const money = (v) => Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const taxAmount = (row) => Math.round(((Number(row.quantity || 0) * Number(row.rate || 0) - Number(row.discount_amount || 0)) * Number(row.gst_rate || 0)) / 100);
const expenseTotals = computed(() => {
    let taxable = 0, tax = 0, total = 0;
    expenseForm.items.forEach((i) => { const base = Math.max(0, Number(i.quantity || 0) * Number(i.rate || 0) - Number(i.discount_amount || 0)); taxable += expenseForm.tax_type === 'non_taxable' ? 0 : base; tax += expenseForm.tax_type === 'non_taxable' ? 0 : taxAmount(i); total += base + (expenseForm.tax_type === 'non_taxable' ? 0 : taxAmount(i)) + Number(i.cess_amount || 0); });
    const tds = expenseForm.tds_applicable ? taxable * Number(expenseForm.tds_rate || 0) / 100 : 0;
    return { taxable, tax, total, tds, net: total - tds };
});

const capture = (error) => { errors.value = error?.response?.data?.errors || { form: [error?.response?.data?.message || 'Unable to save.'] }; };
const clearErrors = () => { errors.value = {}; };
const firstError = (field) => errors.value[field]?.[0] || '';
const run = async (fn) => { loading.value = true; try { await fn(); } finally { loading.value = false; } };
const loadRefs = async () => { refs.value = await AccountingApi.expenseReferences(); };
const loadAll = async () => run(async () => {
    await loadRefs();
    expenses.value = (await AccountingApi.expenses(filters)).expenses || [];
    incomes.value = (await AccountingApi.otherIncome(filters)).income || [];
    recurring.value = (await AccountingApi.recurringExpenses()).recurring || [];
    pettyCash.value = (await AccountingApi.pettyCash()).advances || [];
    imports.value = (await AccountingApi.bankStatementImports()).imports || [];
    statementLines.value = (await AccountingApi.bankStatementLines({ bank_account_id: reconForm.bank_account_id || undefined })).lines || [];
    reconciliations.value = (await AccountingApi.bankReconciliations()).reconciliations || [];
    report.value = await AccountingApi.expenseReports(filters);
});
const selectExpenseCategory = () => { const c = refs.value.expense_categories.find((x) => x.id === Number(expenseForm.expense_category_id)); if (c) expenseForm.expense_account_id = c.expense_account_id; };
const selectIncomeCategory = () => { const c = refs.value.income_categories.find((x) => x.id === Number(incomeForm.income_category_id)); if (c) incomeForm.income_account_id = c.income_account_id; };
const addExpenseRow = () => expenseForm.items.push({ expense_category_id: expenseForm.expense_category_id, expense_account_id: expenseForm.expense_account_id, description: '', quantity: 1, rate: 0, discount_amount: 0, gst_rate: 0, cess_amount: 0 });
const addImportRow = () => importForm.lines.push({ transaction_date: new Date().toISOString().slice(0, 10), description: '', reference_number: '', debit_amount: 0, credit_amount: 0, running_balance: '' });
const addReconRow = () => reconForm.items.push({ bank_statement_line_id: '', journal_entry_id: '', matched_amount: 0, match_type: 'manual', remarks: '' });

const saveExpense = async (status = expenseForm.status) => { saving.value = true; clearErrors(); try { expenseForm.status = status; await AccountingApi.saveExpense({ ...expenseForm, items: expenseForm.items.map((i) => ({ ...i, expense_category_id: i.expense_category_id || expenseForm.expense_category_id, expense_account_id: i.expense_account_id || expenseForm.expense_account_id })) }, expenseForm.id); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveIncome = async (status = incomeForm.status) => { saving.value = true; clearErrors(); try { incomeForm.status = status; await AccountingApi.saveOtherIncome({ ...incomeForm }, incomeForm.id); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveExpenseCategory = async () => { saving.value = true; clearErrors(); try { await AccountingApi.saveExpenseCategory({ ...expenseCategoryForm }, expenseCategoryForm.id); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveIncomeCategory = async () => { saving.value = true; clearErrors(); try { await AccountingApi.saveIncomeCategory({ ...incomeCategoryForm }, incomeCategoryForm.id); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveRecurring = async () => { saving.value = true; clearErrors(); try { await AccountingApi.saveRecurringExpense({ ...recurringForm }, recurringForm.id); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const savePetty = async () => { saving.value = true; clearErrors(); try { await AccountingApi.savePettyCash({ ...pettyForm }); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveImport = async () => { saving.value = true; clearErrors(); try { await AccountingApi.saveBankStatementImport({ ...importForm, lines: importForm.lines.map((i) => ({ ...i })) }); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const saveRecon = async () => { saving.value = true; clearErrors(); try { await AccountingApi.saveBankReconciliation({ ...reconForm, items: reconForm.items.map((i) => ({ ...i })) }); await loadAll(); } catch (e) { capture(e); } finally { saving.value = false; } };
const postExpense = async (row) => { saving.value = true; try { await AccountingApi.postExpense(row.id); await loadAll(); } finally { saving.value = false; } };
const postIncome = async (row) => { saving.value = true; try { await AccountingApi.postOtherIncome(row.id); await loadAll(); } finally { saving.value = false; } };
onMounted(loadAll);
</script>

<template>
    <Layout :page="page" :title="title">
        <div class="expense-page">
            <div class="page-heading"><div><span>ACCOUNTING</span><h1>Expenses, Other Income and Bank</h1></div><button :disabled="loading" @click="loadAll">Refresh</button></div>
            <div class="tabs"><button v-for="tab in tabs" :key="tab" :class="{active: activeTab === tab}" @click="activeTab = tab">{{ tab }}</button></div>
            <div v-if="errors.form" class="alert">{{ errors.form[0] }}</div>

            <section v-if="activeTab === 'expenses'" class="panel">
                <div class="toolbar"><input v-model="filters.search" placeholder="Search voucher, party, invoice" @input="loadAll" /><select v-model="filters.status" @change="loadAll"><option value="">All statuses</option><option>draft</option><option>submitted</option><option>posted</option><option>reversed</option></select></div>
                <div class="form-grid"><select v-model="expenseForm.branch_id"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><input v-model="expenseForm.expense_date" type="date" /><select v-model="expenseForm.expense_category_id" @change="selectExpenseCategory"><option value="">Expense Category</option><option v-for="c in refs.expense_categories" :key="c.id" :value="c.id">{{ c.category_name }}</option></select><select v-model="expenseForm.expense_account_id"><option value="">Expense Account</option><option v-for="a in refs.expense_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><select v-model="expenseForm.paid_from_account_id"><option value="">Paid From</option><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="expenseForm.party_name" placeholder="Party Name" /><select v-model="expenseForm.payment_mode"><option>cash</option><option>bank_transfer</option><option>UPI</option><option>card</option><option>cheque</option><option>wallet</option><option>employee_reimbursement</option><option>unpaid</option><option>mixed</option></select><select v-model="expenseForm.payment_status"><option>paid</option><option>partial</option><option>unpaid</option></select></div>
                <div class="line-grid header"><span>Category</span><span>Description</span><span>Qty</span><span>Rate</span><span>Disc</span><span>GST</span><span>Total</span><span></span></div>
                <div v-for="(item, i) in expenseForm.items" :key="i" class="line-grid"><select v-model="item.expense_category_id"><option value="">Category</option><option v-for="c in refs.expense_categories" :key="c.id" :value="c.id">{{ c.category_name }}</option></select><input v-model="item.description" placeholder="Description" /><input v-model.number="item.quantity" type="number" step="0.001" /><input v-model.number="item.rate" type="number" step="0.01" /><input v-model.number="item.discount_amount" type="number" step="0.01" /><input v-model.number="item.gst_rate" type="number" step="0.01" /><strong>Rs. {{ money((item.quantity * item.rate - item.discount_amount) + taxAmount(item)) }}</strong><button @click="expenseForm.items.splice(i, 1)" :disabled="expenseForm.items.length === 1">Remove</button></div>
                <div class="actions"><button @click="addExpenseRow">Add Row</button><span>Taxable Rs. {{ money(expenseTotals.taxable) }}</span><span>Tax Rs. {{ money(expenseTotals.tax) }}</span><span>TDS Rs. {{ money(expenseTotals.tds) }}</span><strong>Net Rs. {{ money(expenseTotals.net) }}</strong><button :disabled="saving" @click="saveExpense('draft')">Save Draft</button><button :disabled="saving" @click="saveExpense('posted')">Approve and Post</button></div>
                <p v-if="firstError('items')" class="field-error">{{ firstError('items') }}</p>
                <div class="table-wrapper"><table><thead><tr><th>No.</th><th>Date</th><th>Category</th><th>Party</th><th>Paid From</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="e in expenses" :key="e.id"><td>{{ e.voucher_number }}</td><td>{{ e.expense_date }}</td><td>{{ e.category?.category_name }}</td><td>{{ e.party_name || e.supplier?.name || '-' }}</td><td>{{ e.paid_from_account?.account_name || 'Payable' }}</td><td>Rs. {{ money(e.total_amount) }}</td><td>{{ e.payment_status }}</td><td>{{ e.status }}</td><td><button v-if="['draft','submitted'].includes(e.status)" @click="postExpense(e)">Post</button></td></tr></tbody></table></div>
            </section>

            <section v-if="activeTab === 'income'" class="panel">
                <div class="form-grid"><select v-model="incomeForm.branch_id"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><input v-model="incomeForm.income_date" type="date" /><select v-model="incomeForm.income_category_id" @change="selectIncomeCategory"><option value="">Income Category</option><option v-for="c in refs.income_categories" :key="c.id" :value="c.id">{{ c.category_name }}</option></select><select v-model="incomeForm.income_account_id"><option value="">Income Account</option><option v-for="a in refs.income_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><select v-model="incomeForm.received_into_account_id"><option value="">Received Into</option><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="incomeForm.party_name" placeholder="Party" /><input v-model.number="incomeForm.taxable_amount" type="number" placeholder="Taxable" /><input v-model.number="incomeForm.total_amount" type="number" placeholder="Total" /></div>
                <div class="actions"><button :disabled="saving" @click="saveIncome('draft')">Save Draft</button><button :disabled="saving" @click="saveIncome('posted')">Approve and Post</button></div>
                <div class="table-wrapper"><table><thead><tr><th>No.</th><th>Date</th><th>Category</th><th>Party</th><th>Received Into</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="i in incomes" :key="i.id"><td>{{ i.voucher_number }}</td><td>{{ i.income_date }}</td><td>{{ i.category?.category_name }}</td><td>{{ i.party_name || i.customer?.customer_name || '-' }}</td><td>{{ i.received_into_account?.account_name }}</td><td>Rs. {{ money(i.total_amount) }}</td><td>{{ i.status }}</td><td><button v-if="['draft','submitted'].includes(i.status)" @click="postIncome(i)">Post</button></td></tr></tbody></table></div>
            </section>

            <section v-if="activeTab === 'categories'" class="panel split">
                <div><h3>Expense Categories</h3><div class="form-grid two"><input v-model="expenseCategoryForm.category_code" placeholder="Code" /><input v-model="expenseCategoryForm.category_name" placeholder="Name" /><select v-model="expenseCategoryForm.expense_account_id"><option value="">Expense Account</option><option v-for="a in refs.expense_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><button :disabled="saving" @click="saveExpenseCategory">Save</button></div></div>
                <div><h3>Income Categories</h3><div class="form-grid two"><input v-model="incomeCategoryForm.category_code" placeholder="Code" /><input v-model="incomeCategoryForm.category_name" placeholder="Name" /><select v-model="incomeCategoryForm.income_account_id"><option value="">Income Account</option><option v-for="a in refs.income_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><button :disabled="saving" @click="saveIncomeCategory">Save</button></div></div>
            </section>

            <section v-if="activeTab === 'recurring'" class="panel"><div class="form-grid"><input v-model="recurringForm.template_name" placeholder="Template Name" /><select v-model="recurringForm.expense_category_id"><option value="">Category</option><option v-for="c in refs.expense_categories" :key="c.id" :value="c.id">{{ c.category_name }}</option></select><select v-model="recurringForm.expense_account_id"><option value="">Expense Account</option><option v-for="a in refs.expense_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><select v-model="recurringForm.frequency"><option>daily</option><option>weekly</option><option>monthly</option><option>quarterly</option><option>half_yearly</option><option>yearly</option><option>custom</option></select><input v-model.number="recurringForm.amount" type="number" placeholder="Amount" /><input v-model="recurringForm.next_run_date" type="date" /><select v-model="recurringForm.status"><option>active</option><option>paused</option><option>stopped</option></select><button :disabled="saving" @click="saveRecurring">Save Template</button></div><div class="table-wrapper"><table><tbody><tr v-for="r in recurring" :key="r.id"><td>{{ r.template_name }}</td><td>{{ r.frequency }}</td><td>{{ r.next_run_date }}</td><td>Rs. {{ money(r.amount) }}</td><td>{{ r.status }}</td></tr></tbody></table></div></section>

            <section v-if="activeTab === 'petty cash'" class="panel"><div class="form-grid"><select v-model="pettyForm.branch_id"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><input v-model="pettyForm.employee_id" placeholder="Employee ID" /><select v-model="pettyForm.cash_account_id"><option value="">Cash Account</option><option v-for="a in refs.cash_bank_accounts.filter(a => a.account_type === 'cash')" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="pettyForm.advance_date" type="date" /><input v-model.number="pettyForm.amount" type="number" placeholder="Amount" /><input v-model="pettyForm.purpose" placeholder="Purpose" /><select v-model="pettyForm.status"><option>draft</option><option>issued</option></select><button :disabled="saving" @click="savePetty">Save Advance</button></div><div class="table-wrapper"><table><tbody><tr v-for="p in pettyCash" :key="p.id"><td>{{ p.voucher_number }}</td><td>{{ p.advance_date }}</td><td>Employee #{{ p.employee_id }}</td><td>Rs. {{ money(p.amount) }}</td><td>{{ p.status }}</td></tr></tbody></table></div></section>

            <section v-if="activeTab === 'bank import'" class="panel"><div class="form-grid"><select v-model="importForm.bank_account_id"><option value="">Bank Account</option><option v-for="a in refs.cash_bank_accounts.filter(a => a.account_type === 'bank')" :key="a.id" :value="a.id">{{ a.account_name }} {{ a.masked_account_number || '' }}</option></select><input v-model="importForm.file_name" placeholder="Statement File Name" /><input v-model="importForm.statement_start_date" type="date" /><input v-model="importForm.statement_end_date" type="date" /></div><div v-for="(line, i) in importForm.lines" :key="i" class="line-grid import"><input v-model="line.transaction_date" type="date" /><input v-model="line.description" placeholder="Description" /><input v-model="line.reference_number" placeholder="Reference" /><input v-model.number="line.debit_amount" type="number" placeholder="Debit" /><input v-model.number="line.credit_amount" type="number" placeholder="Credit" /><button @click="importForm.lines.splice(i, 1)" :disabled="importForm.lines.length === 1">Remove</button></div><div class="actions"><button @click="addImportRow">Add Line</button><button :disabled="saving" @click="saveImport">Import Lines</button></div><div class="table-wrapper"><table><tbody><tr v-for="i in imports" :key="i.id"><td>{{ i.file_name }}</td><td>{{ i.bank_account?.account_name }}</td><td>{{ i.imported_rows }}/{{ i.total_rows }}</td><td>{{ i.duplicate_rows }} duplicates</td></tr></tbody></table></div></section>

            <section v-if="activeTab === 'reconciliation'" class="panel"><div class="form-grid"><select v-model="reconForm.bank_account_id" @change="loadAll"><option value="">Bank Account</option><option v-for="a in refs.cash_bank_accounts.filter(a => a.account_type === 'bank')" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="reconForm.statement_start_date" type="date" /><input v-model="reconForm.statement_end_date" type="date" /><input v-model.number="reconForm.statement_closing_balance" type="number" placeholder="Statement Closing" /></div><div v-for="(item, i) in reconForm.items" :key="i" class="line-grid recon"><select v-model="item.bank_statement_line_id"><option value="">Statement Line</option><option v-for="l in statementLines" :key="l.id" :value="l.id">{{ l.transaction_date }} {{ l.description }} Dr {{ l.debit_amount }} Cr {{ l.credit_amount }}</option></select><input v-model="item.journal_entry_id" placeholder="Journal Entry ID" /><input v-model.number="item.matched_amount" type="number" placeholder="Matched Amount" /><select v-model="item.match_type"><option>manual</option><option>auto</option><option>partial</option><option>one_to_many</option><option>many_to_one</option></select><button @click="reconForm.items.splice(i, 1)" :disabled="reconForm.items.length === 1">Remove</button></div><div class="actions"><button @click="addReconRow">Add Match</button><button :disabled="saving" @click="saveRecon">Save Reconciliation</button></div><div class="table-wrapper"><table><tbody><tr v-for="r in reconciliations" :key="r.id"><td>{{ r.bank_account?.account_name }}</td><td>{{ r.statement_end_date }}</td><td>Statement Rs. {{ money(r.statement_closing_balance) }}</td><td>Ledger Rs. {{ money(r.ledger_closing_balance) }}</td><td>Diff Rs. {{ money(r.difference_amount) }}</td></tr></tbody></table></div></section>

            <section v-if="activeTab === 'reports'" class="panel split"><div><h3>Expense Summary</h3><p>Total: Rs. {{ money(report.expense_summary.total) }}</p><p>Taxable: Rs. {{ money(report.expense_summary.taxable) }}</p><p>Input GST: Rs. {{ money(report.expense_summary.tax) }}</p><p>Unpaid: Rs. {{ money(report.expense_summary.unpaid) }}</p></div><div><h3>Other Income Summary</h3><p>Total: Rs. {{ money(report.income_summary.total) }}</p><p>Taxable: Rs. {{ money(report.income_summary.taxable) }}</p><p>Output GST: Rs. {{ money(report.income_summary.tax) }}</p></div></section>
        </div>
    </Layout>
</template>

<style scoped>
.expense-page{padding:4px 0 28px}.page-heading,.toolbar,.actions,.tabs{display:flex;align-items:center;gap:12px}.page-heading{justify-content:space-between;margin-bottom:18px}.page-heading span{color:#2457d6;font-size:10px;font-weight:800;letter-spacing:1.2px}.page-heading h1{margin:0;color:#142139}.tabs{flex-wrap:wrap;margin-bottom:14px}.tabs button.active{background:#173b77;color:#fff;border-color:#173b77}.panel{margin-bottom:18px;padding:18px;background:#fff;border:1px solid #dfe6ef;border-radius:8px}.split{display:grid;grid-template-columns:1fr 1fr;gap:18px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.form-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.line-grid{display:grid;grid-template-columns:1.1fr 1.6fr .7fr .8fr .8fr .7fr .9fr .7fr;gap:8px;align-items:center;margin-bottom:8px}.line-grid.import{grid-template-columns:1fr 2fr 1fr 1fr 1fr .8fr}.line-grid.recon{grid-template-columns:2fr 1fr 1fr 1fr .8fr}.line-grid.header{color:#69758a;font-size:10px;font-weight:800;text-transform:uppercase}.actions{justify-content:flex-end;flex-wrap:wrap;margin:12px 0}input,select,button{min-height:38px;padding:8px 10px;color:#344159;background:#fff;border:1px solid #d8e0eb;border-radius:8px;font-size:12px}button{font-weight:750;cursor:pointer}button:disabled{cursor:not-allowed;opacity:.55}.alert,.field-error{padding:10px 12px;margin-bottom:12px;border-radius:8px;background:#fff4f4;color:#b42318;border:1px solid #ffd5d5;font-size:12px}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{padding:11px 10px;border-bottom:1px solid #edf1f5;text-align:left;white-space:nowrap;font-size:12px}th{color:#69758a;background:#f8fafc;font-size:10px;text-transform:uppercase}@media(max-width:1000px){.form-grid,.form-grid.two,.split{grid-template-columns:1fr}.line-grid,.line-grid.import,.line-grid.recon{grid-template-columns:1fr}.page-heading,.toolbar{align-items:stretch;flex-direction:column}}
</style>
