<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import Layout from '../Layout.vue';
import AccountingApi from './AccountingApi';

defineProps({ page: { type: String, default: 'vouchers' }, title: { type: String, default: 'Accounting Vouchers' } });
const today = new Date().toISOString().slice(0, 10);
const refs = ref({ accounts: [], cash_bank_accounts: [], customers: [], suppliers: [], branches: [] });
const journals = ref([]); const receipts = ref([]); const payments = ref([]); const tab = ref('receipt'); const saving = ref(false);
const receipt = reactive({ branch_id: '', customer_id: '', receipt_date: today, receipt_mode: 'cash', cash_bank_account_id: '', amount: 0, discount_allowed: 0, write_off_amount: 0, reference_number: '', remarks: '', status: 'approved', allocations: [] });
const payment = reactive({ branch_id: '', supplier_id: '', payment_date: today, payment_mode: 'cash', cash_bank_account_id: '', amount: 0, discount_received: 0, write_off_amount: 0, reference_number: '', remarks: '', status: 'approved', allocations: [] });
const contra = reactive({ voucher_date: today, from_account_id: '', to_account_id: '', amount: 0, reference_number: '', remarks: '' });
const journal = reactive({ voucher_type: 'journal', voucher_date: today, reference_number: '', narration: '', status: 'approved', entries: [{ account_id: '', debit_amount: 0, credit_amount: 0, narration: '' }, { account_id: '', debit_amount: 0, credit_amount: 0, narration: '' }] });
const totals = computed(() => ({ debit: journal.entries.reduce((s, e) => s + Number(e.debit_amount || 0), 0), credit: journal.entries.reduce((s, e) => s + Number(e.credit_amount || 0), 0) }));
const load = async () => { refs.value = await AccountingApi.references(); receipt.cash_bank_account_id = receipt.cash_bank_account_id || refs.value.cash_bank_accounts?.[0]?.id || ''; payment.cash_bank_account_id = payment.cash_bank_account_id || refs.value.cash_bank_accounts?.[0]?.id || ''; const jr = await AccountingApi.journals(); journals.value = jr.journals || []; const rr = await AccountingApi.receipts(); receipts.value = rr.receipts || []; const pr = await AccountingApi.payments(); payments.value = pr.payments || []; };
const saveReceipt = async () => { saving.value = true; try { await AccountingApi.saveReceipt({ ...receipt }); await load(); } finally { saving.value = false; } };
const savePayment = async () => { saving.value = true; try { await AccountingApi.savePayment({ ...payment }); await load(); } finally { saving.value = false; } };
const saveContra = async () => { saving.value = true; try { await AccountingApi.saveContra({ ...contra }); await load(); } finally { saving.value = false; } };
const saveJournal = async () => { saving.value = true; try { await AccountingApi.saveJournal({ ...journal }); await load(); } finally { saving.value = false; } };
const addLine = () => journal.entries.push({ account_id: '', debit_amount: 0, credit_amount: 0, narration: '' });
const removeLine = (i) => journal.entries.splice(i, 1);
const reverse = async (row) => { const remarks = prompt('Reversal remarks'); if (remarks) { await AccountingApi.reverseJournal(row.id, remarks); await load(); } };
const money = (v) => Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
onMounted(load);
</script>

<template>
    <Layout :page="page" :title="title">
        <div class="acct-page">
            <div class="page-heading"><div><span>ACCOUNTING</span><h1>Vouchers</h1><p>Customer receipts, supplier payments, contra and manual journals.</p></div></div>
            <section class="tabs"><button :class="{active:tab==='receipt'}" @click="tab='receipt'">Receipt</button><button :class="{active:tab==='payment'}" @click="tab='payment'">Payment</button><button :class="{active:tab==='contra'}" @click="tab='contra'">Contra</button><button :class="{active:tab==='journal'}" @click="tab='journal'">Journal</button></section>
            <section v-if="tab==='receipt'" class="panel"><div class="form-grid"><select v-model="receipt.customer_id"><option value="">Customer</option><option v-for="c in refs.customers" :key="c.id" :value="c.id">{{ c.customer_name }}</option></select><input v-model="receipt.receipt_date" type="date" /><select v-model="receipt.receipt_mode"><option value="cash">Cash</option><option value="bank_transfer">Bank</option><option value="upi">UPI</option><option value="card">Card</option><option value="cheque">Cheque</option></select><select v-model="receipt.cash_bank_account_id"><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="receipt.amount" type="number" placeholder="Amount" /><input v-model="receipt.discount_allowed" type="number" placeholder="Discount" /><input v-model="receipt.write_off_amount" type="number" placeholder="Write off" /><input v-model="receipt.reference_number" placeholder="Reference" /><button :disabled="saving" @click="saveReceipt">Save Receipt</button></div></section>
            <section v-if="tab==='payment'" class="panel"><div class="form-grid"><select v-model="payment.supplier_id"><option value="">Supplier</option><option v-for="s in refs.suppliers" :key="s.id" :value="s.id">{{ s.supplier_name || s.name }}</option></select><input v-model="payment.payment_date" type="date" /><select v-model="payment.payment_mode"><option value="cash">Cash</option><option value="bank_transfer">Bank</option><option value="upi">UPI</option><option value="card">Card</option><option value="cheque">Cheque</option></select><select v-model="payment.cash_bank_account_id"><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="payment.amount" type="number" placeholder="Amount" /><input v-model="payment.discount_received" type="number" placeholder="Discount" /><input v-model="payment.write_off_amount" type="number" placeholder="Write off" /><input v-model="payment.reference_number" placeholder="Reference" /><button :disabled="saving" @click="savePayment">Save Payment</button></div></section>
            <section v-if="tab==='contra'" class="panel"><div class="form-grid"><input v-model="contra.voucher_date" type="date" /><select v-model="contra.from_account_id"><option value="">From Account</option><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><select v-model="contra.to_account_id"><option value="">To Account</option><option v-for="a in refs.cash_bank_accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><input v-model="contra.amount" type="number" placeholder="Amount" /><input v-model="contra.reference_number" placeholder="Reference" /><input v-model="contra.remarks" placeholder="Remarks" /><button :disabled="saving" @click="saveContra">Post Contra</button></div></section>
            <section v-if="tab==='journal'" class="panel"><div class="form-grid"><input v-model="journal.voucher_date" type="date" /><input v-model="journal.reference_number" placeholder="Reference" /><input v-model="journal.narration" placeholder="Narration" /><select v-model="journal.status"><option value="draft">Draft</option><option value="approved">Post</option></select></div><div class="table-wrapper"><table><thead><tr><th>Account</th><th>Debit</th><th>Credit</th><th>Narration</th><th></th></tr></thead><tbody><tr v-for="(line,i) in journal.entries" :key="i"><td><select v-model="line.account_id"><option value="">Account</option><option v-for="a in refs.accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select></td><td><input v-model="line.debit_amount" type="number" /></td><td><input v-model="line.credit_amount" type="number" /></td><td><input v-model="line.narration" /></td><td><button @click="removeLine(i)">Remove</button></td></tr></tbody></table></div><div class="totals"><span>Debit Rs. {{ money(totals.debit) }}</span><span>Credit Rs. {{ money(totals.credit) }}</span><span>Difference Rs. {{ money(totals.debit - totals.credit) }}</span><button @click="addLine">Add Row</button><button :disabled="saving || totals.debit !== totals.credit" @click="saveJournal">Save Journal</button></div></section>
            <section class="panel"><h3>Recent Journals</h3><div class="table-wrapper"><table><thead><tr><th>No</th><th>Date</th><th>Type</th><th>Debit</th><th>Credit</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="j in journals" :key="j.id"><td>{{ j.voucher_number }}</td><td>{{ j.voucher_date }}</td><td>{{ j.voucher_type }}</td><td>Rs. {{ money(j.total_debit) }}</td><td>Rs. {{ money(j.total_credit) }}</td><td>{{ j.status }}</td><td><button v-if="['approved','posted'].includes(j.status)" @click="reverse(j)">Reverse</button></td></tr></tbody></table></div></section>
        </div>
    </Layout>
</template>

<style scoped>
.acct-page{padding:4px 0 28px}.page-heading,.tabs,.totals{display:flex;align-items:center;gap:10px}.page-heading{justify-content:space-between;margin-bottom:18px}.page-heading span{color:#2457d6;font-size:10px;font-weight:800;letter-spacing:1.2px}.page-heading h1{margin:0;color:#142139}.page-heading p{margin:6px 0 0;color:#758197;font-size:13px}.tabs{margin-bottom:12px}.tabs .active{color:#fff;background:#2457d6;border-color:#2457d6}.panel{margin-bottom:18px;padding:18px;background:#fff;border:1px solid #dfe6ef;border-radius:8px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}input,select,button{min-height:38px;padding:8px 10px;color:#344159;background:#fff;border:1px solid #d8e0eb;border-radius:8px;font-size:12px}button{font-weight:750;cursor:pointer}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:11px 10px;border-bottom:1px solid #edf1f5;text-align:left;white-space:nowrap;font-size:12px}th{color:#69758a;background:#f8fafc;font-size:10px;text-transform:uppercase}.totals{justify-content:flex-end;margin-top:12px}@media(max-width:900px){.form-grid{grid-template-columns:1fr}.tabs,.totals{align-items:stretch;flex-direction:column}}
</style>
