<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import Layout from '../Layout.vue';
import PayrollApi from './PayrollApi';

defineProps({ page: { type: String, default: 'payroll' }, title: { type: String, default: 'Payroll' } });

const today = new Date().toISOString().slice(0, 10);
const monthStart = today.slice(0, 8) + '01';
const tab = ref('dashboard');
const loading = ref(false);
const saving = ref(false);
const errors = ref({});
const refs = ref({ accounts: [], branches: [], departments: [], designations: [], grades: [], salary_components: [], salary_structures: [], leave_types: [], employees: [], settings: {} });
const dashboard = ref({});
const employees = ref([]);
const attendanceRows = ref([]);
const runs = ref([]);
const reports = ref({});
const filters = reactive({ search: '', branch_id: '', department_id: '', employment_status: '' });

const employee = reactive({ branch_id: '', employee_code: '', first_name: '', middle_name: '', last_name: '', display_name: '', mobile: '', email: '', department_id: '', designation_id: '', employment_type: 'permanent', employment_status: 'active', joining_date: today, last_working_date: '', payroll_status: 'included', payment_mode: 'bank_transfer', bank_account_name: '', bank_account_number: '', bank_name: '', bank_ifsc: '', pan: '', aadhaar_masked: '', uan: '', pf_number: '', esi_number: '', tax_regime: '', status: 'active' });
const department = reactive({ department_code: '', department_name: '', branch_id: '', parent_id: '', status: 'active' });
const designation = reactive({ designation_code: '', designation_name: '', grade_id: '', description: '', status: 'active' });
const grade = reactive({ grade_code: '', grade_name: '', level_number: '', minimum_salary: '', maximum_salary: '', status: 'active' });
const component = reactive({ component_code: '', component_name: '', component_type: 'earning', calculation_type: 'fixed', default_value: 0, taxable: true, statutory: false, recurring: true, attendance_dependent: false, include_in_gross: true, include_in_ctc: true, include_in_net_pay: true, employer_contribution: false, status: 'active' });
const structure = reactive({ structure_code: '', structure_name: '', grade_id: '', employment_type: '', effective_from: today, effective_to: '', annual_ctc: 0, monthly_gross: 0, description: '', status: 'draft', components: [{ salary_component_id: '', calculation_type: 'fixed', fixed_amount: 0, monthly_amount: 0, annual_amount: 0 }] });
const assignment = reactive({ employee_id: '', salary_structure_id: '', effective_from: today, effective_to: '', annual_ctc: '', monthly_gross: '', monthly_net_estimate: '', reason: 'Initial assignment' });
const attendance = reactive({ employee_id: '', attendance_date: today, first_in_at: '', last_out_at: '', attendance_status: 'present', shift_id: '', source: 'manual', remarks: '' });
const payrollRun = reactive({ branch_id: '', period_start: monthStart, period_end: today, payment_date: today, financial_year: '2026-27', run_type: 'regular', status: 'calculated' });
const payment = reactive({ payroll_run_id: '', payment_date: today, payment_mode: 'bank_transfer', bank_account_id: '', status: 'draft' });
const advance = reactive({ employee_id: '', advance_date: today, amount: 0, payment_account_id: '', reason: '', status: 'draft' });
const loan = reactive({ employee_id: '', loan_date: today, principal_amount: 0, interest_rate: 0, interest_method: 'flat', tenure_months: 12, payment_account_id: '', reason: '', status: 'draft' });

const tabs = ['dashboard', 'employees', 'masters', 'attendance', 'salary', 'payroll', 'payslips', 'loans', 'reports'];
const money = (v) => Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const firstError = computed(() => errors.value.form?.[0] || Object.values(errors.value)[0]?.[0] || '');
const capture = (e) => { errors.value = e?.response?.data?.errors || { form: [e?.response?.data?.message || 'Unable to save.'] }; };
const runAction = async (fn) => { saving.value = true; errors.value = {}; try { await fn(); await load(); } catch (e) { capture(e); } finally { saving.value = false; } };
const employeeName = (id) => refs.value.employees.find((e) => Number(e.id) === Number(id))?.display_name || '';
const addStructureLine = () => structure.components.push({ salary_component_id: '', calculation_type: 'fixed', fixed_amount: 0, monthly_amount: 0, annual_amount: 0 });
const syncStructureLine = (line) => { const amount = Number(line.monthly_amount || line.fixed_amount || 0); line.monthly_amount = amount; line.annual_amount = amount * 12; structure.monthly_gross = structure.components.reduce((sum, item) => sum + Number(item.monthly_amount || 0), 0); structure.annual_ctc = structure.monthly_gross * 12; };
const exportCsv = (rows, name) => { const data = rows || []; const headers = Object.keys(data[0] || { empty: '' }).filter((h) => typeof data[0]?.[h] !== 'object'); const csv = [headers.join(','), ...data.map((r) => headers.map((h) => `"${String(r[h] ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = name; link.click(); };

const load = async () => {
    loading.value = true;
    try {
        refs.value = await PayrollApi.references();
        dashboard.value = await PayrollApi.dashboard();
        employees.value = (await PayrollApi.employees(filters)).employees || [];
        attendanceRows.value = (await PayrollApi.attendance()).attendance || [];
        runs.value = (await PayrollApi.runs()).runs || [];
        reports.value = await PayrollApi.reports();
    } finally { loading.value = false; }
};
const saveEmployee = () => runAction(() => PayrollApi.saveEmployee({ ...employee, display_name: employee.display_name || `${employee.first_name} ${employee.last_name}`.trim() }));
const saveDepartment = () => runAction(() => PayrollApi.saveMaster('department', { ...department }));
const saveDesignation = () => runAction(() => PayrollApi.saveMaster('designation', { ...designation }));
const saveGrade = () => runAction(() => PayrollApi.saveMaster('grade', { ...grade }));
const saveComponent = () => runAction(() => PayrollApi.saveMaster('component', { ...component }));
const saveStructure = (status) => runAction(() => PayrollApi.saveSalaryStructure({ ...structure, status, components: structure.components.map((i) => ({ ...i })) }));
const assignSalary = () => runAction(() => PayrollApi.assignSalary({ ...assignment }));
const saveAttendance = () => runAction(() => PayrollApi.saveAttendance({ ...attendance }));
const createRun = (status) => runAction(() => PayrollApi.createRun({ ...payrollRun, status }));
const postRun = (row) => runAction(() => PayrollApi.postRun(row.id));
const generatePayslips = (row) => runAction(() => PayrollApi.payslips(row.id));
const savePaymentBatch = (status) => runAction(() => PayrollApi.paymentBatch({ ...payment, status }));
const saveAdvance = () => runAction(() => PayrollApi.advance({ ...advance }));
const saveLoan = () => runAction(() => PayrollApi.loan({ ...loan }));
onMounted(load);
</script>

<template>
  <Layout page="payroll" title="Payroll">
    <div class="payroll-page">
      <div class="page-heading"><div><span>HR PAYROLL</span><h1>Payroll, Attendance & Payslips</h1><p>Employee master, salary structures, attendance-based payroll, accounting posting and reports.</p></div><button :disabled="loading" @click="load">Refresh</button></div>
      <div class="filters"><input v-model="filters.search" placeholder="Search employee, code, mobile" @keyup.enter="load" /><select v-model="filters.branch_id" @change="load"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><select v-model="filters.department_id" @change="load"><option value="">Department</option><option v-for="d in refs.departments" :key="d.id" :value="d.id">{{ d.department_name }}</option></select><select v-model="filters.employment_status" @change="load"><option value="">Employment status</option><option>active</option><option>notice_period</option><option>resigned</option><option>terminated</option><option>inactive</option></select></div>
      <div class="tabs"><button v-for="t in tabs" :key="t" :class="{ active: tab === t }" @click="tab = t">{{ t }}</button></div>
      <div v-if="firstError" class="alert">{{ firstError }}</div>

      <section v-if="tab === 'dashboard'" class="panel cards"><div><span>Active Employees</span><strong>{{ dashboard.active_employees || 0 }}</strong></div><div><span>In Payroll</span><strong>{{ dashboard.payroll_employees || 0 }}</strong></div><div><span>Gross Payroll</span><strong>Rs. {{ money(dashboard.gross_payroll) }}</strong></div><div><span>Net Payroll</span><strong>Rs. {{ money(dashboard.net_payroll) }}</strong></div><div><span>Deductions</span><strong>Rs. {{ money(dashboard.total_deductions) }}</strong></div><div><span>Employer Cost</span><strong>Rs. {{ money(dashboard.employer_contributions) }}</strong></div><div><span>Pending Attendance</span><strong>{{ dashboard.pending_attendance || 0 }}</strong></div><div><span>Pending Leave</span><strong>{{ dashboard.pending_leave || 0 }}</strong></div><div><span>Exceptions</span><strong>{{ dashboard.payroll_exceptions || 0 }}</strong></div><div><span>On Hold</span><strong>{{ dashboard.salary_on_hold || 0 }}</strong></div><div><span>Loans</span><strong>Rs. {{ money(dashboard.loans_outstanding) }}</strong></div><div><span>Advances</span><strong>Rs. {{ money(dashboard.advances_outstanding) }}</strong></div></section>

      <section v-if="tab === 'employees'" class="panel">
        <div class="form-grid"><select v-model="employee.branch_id"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><input v-model="employee.employee_code" placeholder="Employee code" /><input v-model="employee.first_name" placeholder="First name" /><input v-model="employee.last_name" placeholder="Last name" /><input v-model="employee.mobile" placeholder="Mobile" /><input v-model="employee.email" placeholder="Work email" /><select v-model="employee.department_id"><option value="">Department</option><option v-for="d in refs.departments" :key="d.id" :value="d.id">{{ d.department_name }}</option></select><select v-model="employee.designation_id"><option value="">Designation</option><option v-for="d in refs.designations" :key="d.id" :value="d.id">{{ d.designation_name }}</option></select><select v-model="employee.employment_type"><option>permanent</option><option>probation</option><option>contract</option><option>temporary</option><option>intern</option><option>consultant</option><option>part_time</option><option>daily_wage</option></select><select v-model="employee.employment_status"><option>active</option><option>notice_period</option><option>resigned</option><option>terminated</option><option>retired</option><option>absconded</option><option>inactive</option></select><input v-model="employee.joining_date" type="date" /><select v-model="employee.payroll_status"><option>included</option><option>excluded</option><option>on_hold</option></select><select v-model="employee.payment_mode"><option>bank_transfer</option><option>cash</option><option>cheque</option><option>other</option></select><input v-model="employee.bank_account_number" placeholder="Bank account" /><input v-model="employee.bank_ifsc" placeholder="IFSC" /><input v-model="employee.pan" placeholder="PAN" /></div>
        <div class="actions"><button :disabled="saving" @click="saveEmployee">Save Employee</button></div>
        <div class="table-wrapper"><table><thead><tr><th>Code</th><th>Name</th><th>Branch</th><th>Department</th><th>Designation</th><th>Mobile</th><th>Payroll</th><th>Status</th></tr></thead><tbody><tr v-for="e in employees.data || []" :key="e.id"><td>{{ e.employee_code }}</td><td>{{ e.display_name }}</td><td>{{ e.branch?.name }}</td><td>{{ e.department?.department_name }}</td><td>{{ e.designation?.designation_name }}</td><td>{{ e.mobile }}</td><td>{{ e.payroll_status }}</td><td>{{ e.employment_status }}</td></tr></tbody></table></div>
      </section>

      <section v-if="tab === 'masters'" class="panel split"><div><h3>Department</h3><div class="form-grid two"><input v-model="department.department_code" placeholder="Code" /><input v-model="department.department_name" placeholder="Name" /><select v-model="department.branch_id"><option value="">Branch</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><button :disabled="saving" @click="saveDepartment">Save</button></div></div><div><h3>Designation</h3><div class="form-grid two"><input v-model="designation.designation_code" placeholder="Code" /><input v-model="designation.designation_name" placeholder="Name" /><select v-model="designation.grade_id"><option value="">Grade</option><option v-for="g in refs.grades" :key="g.id" :value="g.id">{{ g.grade_name }}</option></select><button :disabled="saving" @click="saveDesignation">Save</button></div></div><div><h3>Grade</h3><div class="form-grid two"><input v-model="grade.grade_code" placeholder="Code" /><input v-model="grade.grade_name" placeholder="Name" /><input v-model.number="grade.minimum_salary" type="number" placeholder="Min salary" /><input v-model.number="grade.maximum_salary" type="number" placeholder="Max salary" /><button :disabled="saving" @click="saveGrade">Save</button></div></div><div><h3>Salary Component</h3><div class="form-grid two"><input v-model="component.component_code" placeholder="Code" /><input v-model="component.component_name" placeholder="Name" /><select v-model="component.component_type"><option>earning</option><option>deduction</option><option>employer_contribution</option><option>reimbursement</option><option>benefit</option><option>information</option></select><select v-model="component.calculation_type"><option>fixed</option><option>percentage</option><option>formula</option><option>attendance_based</option><option>slab</option><option>manual</option></select><input v-model.number="component.default_value" type="number" step="0.01" placeholder="Default amount" /><label><input v-model="component.attendance_dependent" type="checkbox" /> Attendance dependent</label><button :disabled="saving" @click="saveComponent">Save Component</button></div></div></section>

      <section v-if="tab === 'attendance'" class="panel"><div class="form-grid"><select v-model="attendance.employee_id"><option value="">Employee</option><option v-for="e in refs.employees" :key="e.id" :value="e.id">{{ e.employee_code }} - {{ e.display_name }}</option></select><input v-model="attendance.attendance_date" type="date" /><input v-model="attendance.first_in_at" type="datetime-local" /><input v-model="attendance.last_out_at" type="datetime-local" /><select v-model="attendance.attendance_status"><option>present</option><option>absent</option><option>half_day</option><option>paid_leave</option><option>unpaid_leave</option><option>holiday</option><option>weekly_off</option><option>work_from_home</option><option>on_duty</option><option>travel</option><option>missing_punch</option></select><select v-model="attendance.source"><option>manual</option><option>biometric</option><option>mobile</option><option>web</option><option>imported</option><option>mixed</option></select><textarea v-model="attendance.remarks" placeholder="Remarks"></textarea><button :disabled="saving" @click="saveAttendance">Save Attendance</button></div><div class="table-wrapper"><table><thead><tr><th>Date</th><th>Employee</th><th>Status</th><th>In</th><th>Out</th><th>Minutes</th><th>Source</th></tr></thead><tbody><tr v-for="a in attendanceRows.data || []" :key="a.id"><td>{{ a.attendance_date }}</td><td>{{ a.employee?.display_name }}</td><td>{{ a.attendance_status }}</td><td>{{ a.first_in_at }}</td><td>{{ a.last_out_at }}</td><td>{{ a.payable_minutes }}</td><td>{{ a.source }}</td></tr></tbody></table></div></section>

      <section v-if="tab === 'salary'" class="panel">
        <h3>Salary Structure</h3><div class="form-grid"><input v-model="structure.structure_code" placeholder="Code" /><input v-model="structure.structure_name" placeholder="Name" /><select v-model="structure.grade_id"><option value="">Grade</option><option v-for="g in refs.grades" :key="g.id" :value="g.id">{{ g.grade_name }}</option></select><input v-model="structure.effective_from" type="date" /><input v-model.number="structure.monthly_gross" type="number" step="0.01" placeholder="Monthly gross" readonly /><input v-model.number="structure.annual_ctc" type="number" step="0.01" placeholder="Annual CTC" readonly /><textarea v-model="structure.description" placeholder="Description"></textarea></div>
        <div v-for="(line, idx) in structure.components" :key="idx" class="line-grid"><select v-model="line.salary_component_id"><option value="">Component</option><option v-for="c in refs.salary_components" :key="c.id" :value="c.id">{{ c.component_name }} ({{ c.component_type }})</option></select><select v-model="line.calculation_type"><option>fixed</option><option>percentage</option><option>formula</option><option>attendance_based</option><option>slab</option><option>manual</option></select><input v-model.number="line.monthly_amount" type="number" step="0.01" @input="syncStructureLine(line)" /><input :value="money(line.annual_amount)" readonly /><button :disabled="structure.components.length === 1" @click="structure.components.splice(idx, 1)">Remove</button></div>
        <div class="actions"><button @click="addStructureLine">Add Component</button><button :disabled="saving" @click="saveStructure('draft')">Save Draft</button><button :disabled="saving" @click="saveStructure('approved')">Approve Structure</button></div>
        <h3>Assign Salary</h3><div class="form-grid"><select v-model="assignment.employee_id"><option value="">Employee</option><option v-for="e in refs.employees" :key="e.id" :value="e.id">{{ e.display_name }}</option></select><select v-model="assignment.salary_structure_id"><option value="">Structure</option><option v-for="s in refs.salary_structures" :key="s.id" :value="s.id">{{ s.structure_name }}</option></select><input v-model="assignment.effective_from" type="date" /><input v-model="assignment.effective_to" type="date" /><input v-model.number="assignment.monthly_gross" type="number" placeholder="Override gross" /><textarea v-model="assignment.reason" placeholder="Reason"></textarea><button :disabled="saving" @click="assignSalary">Assign</button></div>
      </section>

      <section v-if="tab === 'payroll'" class="panel"><div class="form-grid"><select v-model="payrollRun.branch_id"><option value="">All branches</option><option v-for="b in refs.branches" :key="b.id" :value="b.id">{{ b.name }}</option></select><input v-model="payrollRun.period_start" type="date" /><input v-model="payrollRun.period_end" type="date" /><input v-model="payrollRun.payment_date" type="date" /><select v-model="payrollRun.run_type"><option>regular</option><option>supplementary</option><option>arrear</option><option>settlement</option></select><button :disabled="saving" @click="createRun('calculated')">Calculate</button><button :disabled="saving" @click="createRun('approved')">Calculate & Approve</button></div><div class="table-wrapper"><table><thead><tr><th>Run</th><th>Period</th><th>Employees</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in runs.data || []" :key="r.id"><td>{{ r.run_number }}</td><td>{{ r.period_start }} to {{ r.period_end }}</td><td>{{ r.employee_count }}</td><td>Rs. {{ money(r.gross_earnings) }}</td><td>Rs. {{ money(r.total_deductions) }}</td><td>Rs. {{ money(r.net_pay) }}</td><td>{{ r.status }}</td><td><button @click="postRun(r)">Post</button><button @click="generatePayslips(r)">Payslips</button></td></tr></tbody></table></div></section>

      <section v-if="tab === 'payslips'" class="panel"><div class="form-grid"><select v-model="payment.payroll_run_id"><option value="">Payroll run</option><option v-for="r in runs.data || []" :key="r.id" :value="r.id">{{ r.run_number }} - Rs. {{ money(r.net_pay) }}</option></select><input v-model="payment.payment_date" type="date" /><select v-model="payment.payment_mode"><option>bank_transfer</option><option>cash</option><option>cheque</option><option>other</option></select><select v-model="payment.bank_account_id"><option value="">Payment account</option><option v-for="a in refs.accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><button :disabled="saving" @click="savePaymentBatch('draft')">Save Batch</button><button :disabled="saving" @click="savePaymentBatch('processed')">Process Payment</button></div><div v-for="r in runs.data || []" :key="r.id" class="payslip-run"><h3>{{ r.run_number }} Payslips</h3><div class="table-wrapper"><table><thead><tr><th>Employee</th><th>Paid Days</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Payslip</th><th>Exceptions</th></tr></thead><tbody><tr v-for="p in r.employee_payrolls || []" :key="p.id"><td>{{ p.employee?.display_name }}</td><td>{{ p.paid_days }}</td><td>Rs. {{ money(p.gross_earnings) }}</td><td>Rs. {{ money(p.total_deductions) }}</td><td>Rs. {{ money(p.net_pay) }}</td><td>{{ p.payslip_number || 'draft' }}</td><td>{{ (p.exceptions_json || []).join(', ') }}</td></tr></tbody></table></div></div></section>

      <section v-if="tab === 'loans'" class="panel split"><div><h3>Employee Advance</h3><div class="form-grid two"><select v-model="advance.employee_id"><option value="">Employee</option><option v-for="e in refs.employees" :key="e.id" :value="e.id">{{ e.display_name }}</option></select><input v-model="advance.advance_date" type="date" /><input v-model.number="advance.amount" type="number" step="0.01" /><select v-model="advance.payment_account_id"><option value="">Payment account</option><option v-for="a in refs.accounts" :key="a.id" :value="a.id">{{ a.account_name }}</option></select><textarea v-model="advance.reason" placeholder="Reason"></textarea><button :disabled="saving" @click="saveAdvance">Save Advance</button></div></div><div><h3>Employee Loan</h3><div class="form-grid two"><select v-model="loan.employee_id"><option value="">Employee</option><option v-for="e in refs.employees" :key="e.id" :value="e.id">{{ e.display_name }}</option></select><input v-model="loan.loan_date" type="date" /><input v-model.number="loan.principal_amount" type="number" step="0.01" /><input v-model.number="loan.tenure_months" type="number" /><input v-model.number="loan.interest_rate" type="number" step="0.0001" /><select v-model="loan.interest_method"><option>flat</option><option>reducing_balance</option><option>interest_free</option></select><textarea v-model="loan.reason" placeholder="Reason"></textarea><button :disabled="saving" @click="saveLoan">Save Loan</button></div></div></section>

      <section v-if="tab === 'reports'" class="panel"><div class="actions"><button @click="exportCsv(reports.employee_register, 'employee-register.csv')">Export Employees</button><button @click="exportCsv(reports.payroll_register, 'payroll-register.csv')">Export Payroll</button><button @click="exportCsv(reports.attendance_summary, 'attendance-summary.csv')">Export Attendance</button></div><div class="cards"><div><span>Unposted Runs</span><strong>{{ reports.reconciliation?.unposted_payroll_runs || 0 }}</strong></div><div><span>Negative Net</span><strong>{{ reports.reconciliation?.negative_net_pay || 0 }}</strong></div><div><span>Missing Payslips</span><strong>{{ reports.reconciliation?.missing_payslips || 0 }}</strong></div></div><div class="table-wrapper"><table><thead><tr><th>Employee</th><th>Department</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Run</th></tr></thead><tbody><tr v-for="p in reports.payroll_register || []" :key="p.id"><td>{{ p.employee?.display_name }}</td><td>{{ p.employee?.department?.department_name }}</td><td>Rs. {{ money(p.gross_earnings) }}</td><td>Rs. {{ money(p.total_deductions) }}</td><td>Rs. {{ money(p.net_pay) }}</td><td>{{ p.run?.run_number }}</td></tr></tbody></table></div></section>
    </div>
  </Layout>
</template>

<style scoped>
.payroll-page{padding:4px 0 28px}.page-heading,.tabs,.actions,.filters{display:flex;align-items:center;gap:12px}.page-heading{justify-content:space-between;margin-bottom:18px}.page-heading span{color:#2457d6;font-size:10px;font-weight:800;letter-spacing:1.2px}.page-heading h1{margin:0;color:#142139}.page-heading p{margin:6px 0 0;color:#758197;font-size:13px}.filters,.tabs{flex-wrap:wrap;margin-bottom:14px}.tabs button.active{background:#173b77;color:#fff;border-color:#173b77}.panel{margin-bottom:18px;padding:18px;background:#fff;border:1px solid #dfe6ef;border-radius:8px}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.cards div{padding:14px;border:1px solid #edf1f5;border-radius:8px}.cards span{display:block;color:#69758a;font-size:11px}.cards strong{display:block;margin-top:6px;color:#142139;font-size:18px}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.form-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.line-grid{display:grid;grid-template-columns:1.7fr 1fr 1fr 1fr .7fr;gap:8px;align-items:center;margin-bottom:8px}.actions{justify-content:flex-end;flex-wrap:wrap;margin:12px 0}input,select,textarea,button{min-height:38px;padding:8px 10px;color:#344159;background:#fff;border:1px solid #d8e0eb;border-radius:8px;font-size:12px}label{display:flex;align-items:center;gap:8px;color:#344159;font-size:12px}button{font-weight:750;cursor:pointer}.alert{padding:10px 12px;margin-bottom:12px;border-radius:8px;background:#fff4f4;color:#b42318;border:1px solid #ffd5d5;font-size:12px}.table-wrapper{overflow-x:auto}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{padding:11px 10px;border-bottom:1px solid #edf1f5;text-align:left;white-space:nowrap;font-size:12px}th{color:#69758a;background:#f8fafc;font-size:10px;text-transform:uppercase}.payslip-run{margin-top:18px}@media(max-width:1000px){.cards,.split,.form-grid,.form-grid.two,.line-grid{grid-template-columns:1fr}.page-heading{align-items:stretch;flex-direction:column}}
</style>
